GET http://localhost:5173/games

###
GET http://localhost:5173/games/1

###
POST http://localhost:5173/games
Content-Type: application/json

{
  "genre": "Kids and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5173/games/4
Content-Type: application/json

{
    "name": "Minecraft for Windows",
    "genre": "Kids and Family",
    "price": 29.99,
    "releaseDate": "2011-11-18"
}

###
DELETE http://localhost:5173/games/2